// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCc9FB2l5bcIuHNYj5n4dKIknch80grGA',
    appId: '1:711772624388:web:7abc973dd2f6a9e5750751',
    messagingSenderId: '711772624388',
    projectId: 'chti-face-bouc-868f0',
    authDomain: 'chti-face-bouc-868f0.firebaseapp.com',
    storageBucket: 'chti-face-bouc-868f0.firebasestorage.app',
    measurementId: 'G-WVKY01BLN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrYt7Eb51JtuCYnFInMsJ5cipygLROQfk',
    appId: '1:711772624388:android:d8c33a0c048b8c71750751',
    messagingSenderId: '711772624388',
    projectId: 'chti-face-bouc-868f0',
    storageBucket: 'chti-face-bouc-868f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgETsMQi9AzbDTqZvmcE_JonXiI3BeKg',
    appId: '1:711772624388:ios:682759f212a063d8750751',
    messagingSenderId: '711772624388',
    projectId: 'chti-face-bouc-868f0',
    storageBucket: 'chti-face-bouc-868f0.firebasestorage.app',
    iosBundleId: 'com.example.chti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfgETsMQi9AzbDTqZvmcE_JonXiI3BeKg',
    appId: '1:711772624388:ios:682759f212a063d8750751',
    messagingSenderId: '711772624388',
    projectId: 'chti-face-bouc-868f0',
    storageBucket: 'chti-face-bouc-868f0.firebasestorage.app',
    iosBundleId: 'com.example.chti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCc9FB2l5bcIuHNYj5n4dKIknch80grGA',
    appId: '1:711772624388:web:d96f788230fb6b91750751',
    messagingSenderId: '711772624388',
    projectId: 'chti-face-bouc-868f0',
    authDomain: 'chti-face-bouc-868f0.firebaseapp.com',
    storageBucket: 'chti-face-bouc-868f0.firebasestorage.app',
    measurementId: 'G-QT7KKQPBE0',
  );
}
